<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\DistributedJobScheduler.Application\DistributedJobScheduler.Application.csproj" /><ProjectReference Include="..\DistributedJobScheduler.Domain\DistributedJobScheduler.Domain.csproj" /></ItemGroup>
</Project>
